global:
  root: /Data/webapps/videodownload
  pid: /var/run/vide/videodownload.pid
  server_post_url: http://service.vmatch.tansuotv.com/youpeng/set_yp_url.php
  server_lasttime_url: http://api.tvad.tansuotv.com/API/yun/youpeng/last_time.php
  server_current_url: http://api.vmatch.tansuotv.com/API/yun/youpeng/check_yp_data.php

device:
  ip: 10.20.40.214
  #device log
  log: /Data/webapps/vide_log/device.log

db:
  name: video
  host: 10.20.40.21
  port: 3306
  user: root
  passwd: zhanglei

video:
  root: /Data/webapps/video

image:
  root: /Data/webapps/video

log:
  root: /Data/webapps/video_log

