global:
  root: /Data/webapps/videodownload
  pid: /var/run/video/videodownload.pid
  log_level: info   #info error debug
  server_post_url: http://service.vmatch.tansuotv.com/youpeng/set_yp_url.php
  server_lasttime_url: http://api.tvad.tansuotv.com/API/yun/youpeng/last_time.php
  server_current_url: http://api.vmatch.tansuotv.com/API/yun/youpeng/check_yp_data.php

#设备信息
device:
  #设备IP
  ip: 10.20.40.214
  #设备日志位置
  log: /Data/webapps/video_log/device.log

#数据库信息
db:
  name: video
  host: 10.20.40.21
  port: 3306
  user: root
  passwd: zhanglei

video:
  root: /Data/webapps/video

image:
  root: /Data/webapps/video

log:
  root: /Data/webapps/video_log
  ffmpeg: /Data/webapps/video_log/ffmpeg_log

monitor:
  mail: zhanglei@tansuotv.com